### ISSUE TITLE
Logitech DualAction - partial success, but no controllers shown/moved in VR view

### ISSUE THREAD

**Issue by mungewell** [puresoul/Barebone#1]
I tried with a Logitech DualAction controller, and there were extra controller icons in the SteamVR status window but the buttons didn't work as described on webpage. Only one button functioned, to re-center the screen.

I couldn't see controllers in the VR view, but maybe they were out of view. I am using VRidge to drive a DIY system, so maybe that is a factor too...
![barebones_logitech_dualaction](https://user-images.githubusercontent.com/236907/99189991-fa503600-275b-11eb-9d35-a737ace6860a.png)

**Comment by mungewell** [comment]
Turns out that the 'gamepad' icon in the screen shot above is a different ("Gamepad") driver, removing this from "C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers" made icon disappear and recentering no longer functioned.

There the other 'C' icons are not functioning at all, other than changing icon shortly after StemVR starts. 

If the "barebones" driver is not installed these 'C' icons do not appear.

**Comment by puresoul** [comment]
Actualy I never tested this driver with vridge hmd and if I remember it right, they got controllers hardcoded with hmd very tight. Now I really can't say where the problem may be, but I used it by that time to be even able to interact with some VR content where you can't use anything but VR controllers. So it was used only with first oculus devkit and then with cv1 for some time, until I bought touch controllers. But this driver was my first experience with openvr so it never for example take into account that you will have your movement interpreted by something else, than hmd gyro. Don't expect to be able to play action games or something like that with it...

**Comment by mungewell** [comment]
Thanks for the reply. Can you confirm which gamepads are known to work? It may be that the Logitech I have is using some other key-schem.

Anyhow I thought your driver was cool and might help out others lacking VR controller hardware....

BTW I am not using the Android VRidge app, I am only using it's PC engine (RiftCat) and this does not automatically present controllers.

Under the install directory there are two 'extra' exes.
`C:\Program Files (x86)\Riftcat 2`

 If you want to attempt; Start 'VRidge.exe", then start SteamVR. This allows SteamVR to run without (real) headset attached and at this point it has no controllers attached.

The "StreamView.exe" extracts the two-eye image to current monitor, which in my case is PSVR on HDMI output. Secret key presses are described here:
https://support.riftcat.com/hc/en-us/articles/115005811189-Moonlight-Advanced-Guide

My script talks the VRidge-API interface and fakes the headset. I can also fake controllers, which I don't do at the moment. Screen grab from another bug report...
![capture_rate_high](https://user-images.githubusercontent.com/236907/99476054-c46fa500-2947-11eb-9a9b-876923e34e94.png)

**Comment by puresoul** [comment]
I only mean it that, they are somehow present also in hmd engine/server, because by that time I tried to use only the vridge controllers and found that about it. Give me some time, I refresh my setup a give it a shot with vridge. Then I'll post my results.

Yes, I was trying similar configuration, but lets call it upside down. To use only vridge vr controller emulation without the hmd functionality. After about 2 weeks of hacking with it I just give up a gone the other way...

**Comment by puresoul** [comment]
to answer your 1st question, I used somehow generic exaple "C++ Xbox 360 gamepad Input using XInput" sourcecode as you can see over here https://github.com/puresoul/Barebone/blob/master/BareboneOpenVRTest/Gamepad.cpp

I was using it with SteelSeries Stratus XL Bluetooth gamepad and it was also working with Virtual Controller api because it was only option for developing through remote desktop.... 

So call it simple, if your device supports XInput, my driver support it, but maybe partially...

Check manual of your gamepad, there is something about Xinput

https://www.logitech.com/assets/35017/gamepad-f310-gsw.pdf

**Comment by puresoul** [comment]
did you enable "activateMultipleDrivers" : true, at Steam\config\steamvr.vrsettings ("steamvr" struct) ?

**Comment by puresoul** [comment]
That isn't the real issue, that you not using VRidge because it is using itself automatically after installation by linking its drivers and configuration into SteamVR. That's how it works in openvr, if driver is present, than it is loaded.... 

I got it to work after edit file Riftcat 2\Config\vridge.cfg and change "Controller.UseControllers": false, then restart steamvr and controllers may  appear somewhere near you.

![vr](https://user-images.githubusercontent.com/2646309/99608029-65746380-2a0d-11eb-89c7-3e63331130b8.png)

**Comment by mungewell** [comment]
I did/do have  "activateMultipleDrivers" : true, as you can see that the "C" icons appear when I have the "barebones" driver enabled, and don't when I don't.

I tried with a Steam Controller (the gamepad one) and, if I repositioned VRidge headset in virtual space, I could see 1 controller (maybe 2 in exactly the same place). It didn't matter if "Controller.UseControllers" was true or false. These rendered Wands disappeared when I disabled the "barebones" driver. 

![barebones_seen](https://user-images.githubusercontent.com/236907/99749173-dd0dc580-2ad5-11eb-8734-5d2b5c956291.png)

BTW this is the script I used for repositioning:
https://github.com/mungewell/pyPSVR/blob/master/example4_vridge_sensors/reposition.py

I'm at a different location for the rest of the week, I'll try again with the Logitech when I can - but I really think that this is an issue with my lack of XBox controllers and not with your driver. 

If it were really critical to me I'd go shopping.... thank you for the driver and the helpful suggestions.

**Comment by puresoul** [comment]
Yes, that's the case, it's two in same position. So looks like you got it working.
